# CKG's Alacritty Config 

#          _                 _ _   _
#     __ _| | __ _  ___ _ __(_) |_| |_ _   _
#   / _` | |/ _` |/ __| '__| | __| __| | | |
#  | (_| | | (_| | (__| |  | | |_| |_| |_| |
#  \__,_|_|\__,_|\___|_|  |_|\__|\__|\__, |
#                                    |___/




# Window Config
window: 
  padding:
    x: 12
    y: 12
  dynamic_padding: false #enables padding as explained in- https://superuser.com/questions/1689645/what-does-the-argument-parameter-dynamic-padding-do-exactly-in-the-alacritty-t

  # Decorations (Example Config- https://sunnnychan.github.io/cheatsheet/linux/config/alacritty.yml.html) 
  decorations: buttonless 
  #decorations: full
  #Full has all window decorations (regular MacOS style), buttonless has no decorations and works on BigSur ["full", "none", "buttonless"]

  # Background Opacity
  #opacity: .9 #if commented out, set to 100%


font:
  normal:
    family: JetBrains Mono NL
# Default on MacOS is Menlo
  size: 12.0


# Color Scheme
#Currently set to Catppuccin 
colors:
  # Default colors
  primary:
    background: '0x0f1419'
    foreground: '0xD9E0EE'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1E1D2F'
    #cursor: '0xF5E0DC' #default
    cursor: '0xC9CBFF'

  # Normal colors
  normal:
    black:   '0x6E6C7E'
    red:     '0xF28FAD'
    green:   '0xABE9B3'
    yellow:  '0xFAE3B0'
    blue:    '0x96CDFB'
    magenta: '0xF5C2E7'
    cyan:    '0x89DCEB' #default cyan color
    #cyan:    '0xC9CBFF' #Lavender color from the git website
  	white:   '0xD9E0EE'

  # Bright colors
  bright:
    black:   '0x988BA2'
    red:     '0xF28FAD'
    green:   '0xABE9B3'
    yellow:  '0xFAE3B0'
    blue:    '0x96CDFB'
    magenta: '0xF5C2E7'
    cyan:    '0x89DCEB'
    white:   '0xD9E0EE'

  indexed_colors:
    - { index: 16, color: '0xF8BD96' }
    - { index: 17, color: '0xF5E0DC' }


