# Catppuccin Theme Below!                                                       
colors:                                                                         
  # Default colors                                                              
  primary:                                                                      
    background: '0x0f1419'                                                      
    foreground: '0xD9E0EE'                                                      
                                                                                
  # Colors the cursor will use if `custom_cursor_colors` is true                
  cursor:                                                                       
    text: '0x1E1D2F'                                                            
    #cursor: '0xF5E0DC' #default                                                
    cursor: '0xC9CBFF'                                                          
                                                                                
  # Normal colors                                                               
  normal:                                                                       
    black:   '0x6E6C7E'                                                         
    red:     '0xF28FAD'                                                         
    green:   '0xABE9B3'                                                         
    yellow:  '0xFAE3B0'                                                         
    blue:    '0x96CDFB'                                                         
    magenta: '0xF5C2E7'                                                         
    cyan:    '0x89DCEB' #default cyan color                                     
    #cyan:    '0xC9CBFF' #Lavender color from the git website                   
    white:   '0xD9E0EE'                                                         
                                                                                
  # Bright colors                                                               
  bright:                                                                       
    black:   '0x988BA2'                                                         
    red:     '0xF28FAD'                                                         
    green:   '0xABE9B3'                                                         
    yellow:  '0xFAE3B0'                                                         
    blue:    '0x96CDFB'                                                         
    magenta: '0xF5C2E7'                                                         
    cyan:    '0x89DCEB'